### ISSUE TITLE
Meta - Reduce the model compilation time

### ISSUE THREAD

**Issue by EmileRolley** [incubateur-ademe/nosgestesclimat#1812]
With the addition of all new region models introduced by #1732, the compilation to translated and optimized json files took a lot of time: ~50s. Consequently, to reduce this time which could slow down the dev workflow we must investigate to find the bottleneck and, if possible, try to remove it.

**Instantiating publicodes engine took in average ~700ms** -> need to reduce the number of instanciations.  

## Current status

```
getTranslatedRules = ~2s
compressRules = ~1.4s * nb_region * nb_lang ~= 22s  
````

It seems that the rules optimization take ~50% of the compilation time. Efforts should be focused on it.

## Strategy to reduce the optimization time

* [x] Parallelize the execution -- see #1818 
* [ ] Use an imperative style and benchmark significative performance improvements?
* [ ] Currently, for each new region, the 90% of the base model is reoptimized. We need to find a way to optimized only one time the major part of the base model.

## Note about using a compiled language

It would seem obvious to use a complied language instead of interpreted script for both the translation and the compilation of the model. However, `rulesToJSON`, currently depends on `getModelFromSource` and `publiopti`, and both of them depends on `publicodes` which is a TS package...
