### ISSUE TITLE
[Meta] Réorganisation du parcours Transport

### ISSUE THREAD

**Issue by JuliePouliquen** [incubateur-ademe/nosgestesclimat#1916]
Le parcours Transport a bien évolué récemment, avec l'intégration de nouveaux véhicules et contextes. Les réflexions par rapport à la longueur des questions sur la voiture, le travail par ailleurs sur la partie logement et l'intégration de questions concernant les vacances nous invitent à repenser le parcours pour être plus fluide et mieux coller aux usages des citoyens. Ce travail est mené par l'équipe modèle + design avec @jeremiecook et @Clemog.

Avec en tête une direction globale définie ici :

- Pour chaque question, proposer **en priorité 4 choix simples**, accessibles en un clic, avec des valeurs pré-remplies *(ce qui implique pour chaque question un choix éditorial fort)*
- Chaque fois que c’est utile, proposer à l’utilisateur d’**aller plus loin** en jouant plus finement avec les paramètres du moteur (parcours “avancé”)
- Indiquer sur chaque réponse un **ordre de grandeur en CO₂**. Reste des **valeurs arrondies** (50kg, 300kg, 1,5t) pour faciliter la comparaison.
- Rendre toujours visible le texte d’**aide à la saisie**, et intégrer un bloc permettant de partager des **informations utiles**. Ces deux blocs remplacent le bouton ℹ️  qui a plusieurs rôles aujourd’hui et cache par défaut l’information qu’on souhaite partager.
- Réécrire les questions avec une **vision “utilisateur”** plutôt que “moteur” (ex: demander un nombre de verres plutôt qu’une quantité en litres)
- **Réorganiser les informations** dans le bloc question. Mettre en valeur les choix par défaut, aligner les contenus à gauche, limiter le nombre de boutons et d’actions.
- **Regrouper les questions** par sujet commun (ex : achats alimentaires, petit déjeuner etc.) et réfléchir à un ordre de questions cohérent

Voici ce qui est prévu (roadmap haut niveau) : 

- [ ] #1917
- [ ] Création d'une mosaïque d'entrée pour chacune des deux sous-parties
- [ ] Groupement de certaines questions concernant la voiture ("Je n'ai pas de voiture" dans "C'est quoi votre voiture ?" entre autres)
- [ ] Passage en format "basique / avancé" pour une grande partie des questions (basique : 4 propositions / avancé : saisie précise)

**Comment by JuliePouliquen** [comment]
En première étape, je me lance dans le nouvel arbre de questions, pour voir quelles questions ça pose, et arbitrer dessus. Une fois d'accord sur cet arbre, nous pourrons nous lancer dans l'implémentation progressive.

**Comment by JuliePouliquen** [comment]
Je clôture au profit de #1951
