### ISSUE TITLE
[Meta] Refonte des personas

### ISSUE THREAD

**Issue by JuliePouliquen** [incubateur-ademe/nosgestesclimat#1944]
Cette refonte a plusieurs buts :

- être plus exhaustifs sur nos modèles (l’idée étant que **chaque option d’une question, comprenant “je ne sais pas”, soit attribuée à un persona de manière cohérente**) cf. #1813 
- vérifier que l’on couvre bien l’ensemble (enfin, un ensemble représentatif) de la population avec nos questions : urbain / rural, ado / adulte / retraité...
- pouvoir utiliser ces personas pour comparer les différents simulateurs existants sur le "marché" cf. #1776 

## Pourquoi des personas ?
Les personas nous sont par ailleurs d'une grande aide pour tester le modèle (dans un sens de développement) : 

- Vérifier que chaque mise à jour du modèle ne "casse" pas les simulations précédentes
- Vérifier que l'impact d'une mise à jour sur les empreintes carbone est cohérent

Ainsi que dans une démarche d'amélioration du parcours action : les personas permettent de vérifier que l'on ne propose pas des actions décalées selon les profils (proposer d'aller au travail à vélo à un retraité, par exemple).

## ToDo list
Voici une proposition de todo list : 

- [x] Créer une liste exhaustive de toutes les règles présentes dans le modèle, choisir un persona qui les a toutes.
- [x] Créer et documenter une liste d'une dizaine de personas représentatifs des options du modèle (dont l'option "je ne sais pas") et représentatifs de la population française (pas dans leur distribution, mais dans leur représentativité : au moins un persona de chaque "type"). _N.B. Nous ne partons pas de zéro ! Une liste de personas existe déjà : il s'agit de l'épurer, la documenter, vérifier sa représentativité._
   - [x] Petit texte explicatif de "qui" est le persona"
   - [x] Grandes idées associées au persona
   - [x] Réponses "cohérentes" au simulateur
- [x] Faire un récap des précédents personas, et des actuels.
- [x] Modifier la page ngc/persona pour expliquer et documenter la démarche liée aux personas, et la façon dont nous les testons et faisons évoluer.

## Issues reliées
Cette issue est liée à : 

- Pour la représentativité : #1261 #1617 #1691 et peut-être #857 ?
- Pour inspiration sur l'amélioration du parcours action : #1586

**Comment by JuliePouliquen** [comment]
Un premier travail a été initié par @Clemog avec https://github.com/incubateur-ademe/nosgestesclimat/pull/1939 dans l'optique de comparer les modèles de simulation d'empreinte, travail de comparaison et convergence mené par @Benjamin-Boisserie-ABC.

**Comment by JuliePouliquen** [comment]
Proposition d'une nouvelle liste de 10 personas-modèle : 

![image](https://github.com/incubateur-ademe/nosgestesclimat/assets/4005340/9746f28a-8563-49c5-a271-f9fba9c708d8)

Les nouveaux personas reprennent en partie les précédents, mais complètent grandement la variabilité de leurs caractéristiques, tout en réduisant leur liste.

Un manque est identifié actuellement sur #1136 #857 : la vie "nomade" sans appartement ou maison fixe. Je me demande comment c'est intégrable à ce jour au simulateur, ce sera un sujet à voir avec @jeremiecook !

Proposition de processus de mise à jour des personas, au fil des éditions du modèle : 

- S’il s’agit d’une modification du modèle :
    - Vérifier : Casse t-elle les réponses précédentes (ex : passage au format quotidien / week-ends pour les transports) ?
        - Si oui : versionnage
    - Vérifier : Casse-t-elle les actions liées à cette partie du modèle ?
        - Si oui : versionnage
    - Vérifier : Les modifications éventuelles des empreintes des personas doivent être cohérente.
    - Si nécessaire : modification de la page personas sur le site
- S’il s’agit d’un ajout au modèle :
    - Ajout de réponses aux personas en procédant comme suit :
        - Chacune des réponses est attribuée à au moins un persona
        - Au moins un persona n’a pas de réponse enregistrée (et sera donc sur la valeur par défaut)
        - Si nous avons créé une ou des actions liée(s) à cet ajout : vérifier que cette action est proposée à au moins un persona
    - Si nécessaire : modification de la page personas sur le site

Cette checklist fait émerger l'idée d'avoir, par persona, la liste d'actions qui lui est proposée.

**Comment by Clemog** [comment]
Je ne suis pas sur de bien comprendre le processus de mis à jour ?

> * Si oui : versionnage

Pour moi, peu importe les conditions, si maj du modèle, nouvelle version des personas

**Comment by JuliePouliquen** [comment]
Récap des personas actuels : 

- Moyenne : 8,4 T // 2 actionw > 1 T // 14 actions > 100 kg
- 2 tonnes : 3 T // 0 action > 1 T // 0 actions > 100 kg
- Corentin de Paris : 4,6 T // 0 action > 1 T // 6 actions > 100 kg
- Sandy de Pacé : 9,8 T // 5 actions > 1 T // 11 actions > 100 kg
- Mehdi d'Agen : 6,7 T // 4 actions > 1 T // 3 actions > 100 kg
- Ximun d'Arcangues : 15 T // 10 actions > 1 T // 9 actions > 100 kg
- Marie de Laval : 11 T // 4 actions > 1 T // 6 actions > 100 kg
- Jessica de Lyon : 8,5 T // 3 actions > 1 T // 3 actions > 100 kg
- Zoé de Damblain : 7,5 T // 2 actions > 1 T // 10 actions > 100 kg
- Nadia de Marseille : 16 T // 7 actions > 1 T // 8 actions > 100 kg
- Serge de Libourne : 12 T // 7 actions > 1 T // 14 actions > 100 kg
- Nolan de Neuilly : 20 T // 10 actions > 1 T // 10 actions > 100 kg
- Eric de Strasbourg : 7,9 T // 2 actions > 1 T // 16 actions > 100 kg

**Comment by JuliePouliquen** [comment]
Coté actions, ces nouveaux personas soulèvent déjà quelques questions : 

- On propose de télétravailler à Anne-Claire qui ne travaille pas.
- On ne propose pas à Gérard d'arrêter les croisières alors que c'est le plus gros poste de son empreinte.
- Nolan est au lycée : il y a beaucoup de choses sur lesquelles il n'a pas la main.

Et réflexion : le poste "loisirs" pourra tout de même sacrément impacter certains (Mehdi, Jessica).

**Comment by JuliePouliquen** [comment]
Suite à discussion avec @Clemog j'ai remis des lieux de vie précis aux personas et mis en cohérence leurs réponses en fonction. Il y a : une variété de personnes vivant dans le sud / nord / est / ouest dont une personne sur une île et une personne à la montagne.
Note : je n'ai pas remis les localisations dans le nom, mais seulement dans la description (elles ne "disent" rien à beaucoup de monde dès qu'il s'agit d'une ville de moins de 20 000 habitants). À discuter.

**Comment by Clemog** [comment]
Je suis tout de même pour garder la ville dans le nom pour le côté plus "humain" mais si tu trouves ça très secondaire, on peut garder l'info au moins dans le résumé

**Comment by JuliePouliquen** [comment]
> Je suis tout de même pour garder la ville dans le nom pour le côté plus "humain" mais si tu trouves ça très secondaire, on peut garder l'info au moins dans le résumé

Je n'ai pas d'avis tranché sur le sujet. J'ai juste peur que les villages ne parlent pas et que ça fasse des noms à rallonge, mais ça me va de les remettre.
