### ISSUE TITLE
[Meta Loisirs] Pratiques sportives

### ISSUE THREAD

**Issue by JuliePouliquen** [incubateur-ademe/nosgestesclimat#1958]
Cette issue est une sous-meta de #1828.
Elle est reliée entre autres à #1311, #1316.

Pour chaque pratique, il convient de retenir qu'il faut généralement sommer : l'empreinte de l'équipement personnel nécessaire (à amortir potentiellement), et l'empreinte liée à l'utilisation d'infrastructures. À noter que la base empreinte dispose des empreintes de beaucoup de ces petits équipements sportifs (voir ci-dessous).

Voici ci-dessous les pratiques sportives listées et à investiguer : 

- [ ] Golf : base empreinte 0,3 kg éq. CO2 / balle + 3,7 kg éq. CO2 / club
- [ ] Équitation : base empreinte 2,6 kg éq. CO2 / bombe + 2,4 kg éq. CO2 / cravache + 24 kg éq. CO2 / harnais + 4 kg éq. CO2 / pantalon + 160 kg éq. CO2 / selle + 4 kg éq. CO2 / veste
- [ ] Natation : base empreinte lunettes + maillot + pince-nez 0,640 kg éq. CO2
- [ ] Aviron
- [ ] Canoe kayak
- [ ] Voile
- [ ] Rugby
- [ ] Handball : base empreinte ballon + short 3,4 kg éq. CO2
- [ ] Patinoire (hockey sur glace, patinage artistique) : quelques données [ici sur une patinoire temporaire extérieure](https://france3-regions.francetvinfo.fr/occitanie/haute-garonne/toulouse/toulouse-scientifiques-s-interrogent-patinoire-du-capitole-periode-rechauffement-climatique-1787165.html)
- [ ] Foot : base empreinte 7 kg éq. CO2 / produit
- [ ] Basket : base empreinte 6,1 kg éq. CO2 / produit
- [ ] Volley : base empreinte 3 kg éq. CO2 / produit
- [ ] Tennis (les terrains sont rarement multi-sports) : base empreinte 23 kg éq. CO2 / produit
- [ ] Planche à voile : base empreinte 220 kg éq. CO2 / produit
- [ ] Ski : on a des données ici #1693 
- [ ] Cyclisme (pour le/les vélos supplémentaires)

Certaines pratiques sont très carbonées car motorisées : 
- [ ] Karting
- [ ] Motocross
- [ ] Jet-ski
- [ ] Saut en parachute
- [ ] Aviation de loisir. Un début de piste [ici](https://mobile.twitter.com/brunojav/status/1365966559945109505)
- [ ] Bateau type voilier (moteur pour le port / manœuvre et quand absence de vent)
- [ ] Bateau à moteur (comprenant ski-nautique / wake-board / barefoot et tutti quanti, hors tirage par câble)

On pourrait juger que les dernières pratiques sont prioritaires à ajouter dans NGC, car très carbonées. En même temps, elles représentent une proportion bien moindre de la population...

**Comment by florianpanchout** [comment]
@JuliePouliquen @Clemog J'enlève cette carte de ce sprint et on verra si on le remet à celui de septembre ?
