### ISSUE TITLE
[Meta Loisirs] Culture

### ISSUE THREAD

**Issue by JuliePouliquen** [incubateur-ademe/nosgestesclimat#1959]
Cette issue est une sous-meta de https://github.com/incubateur-ademe/nosgestesclimat/issues/1828.
Elle est reliée entre autres à #1409 

## Version 1

En première version, nous allons tâcher d'ajouter un matelas à chaque personne qui couvrira les pratiques culturelles (listées pour la version 2), avec une approche macro issue des chiffres du SDES.

## Version 2

Pour affiner, nous essaierons de proposer une approche micro par type de sorties culturelles.
Pour chaque pratique, il convient de retenir qu'il faut généralement sommer : l'empreinte de l'équipement personnel nécessaire (à amortir), et l'empreinte liée à l'utilisation d'infrastructures.

- [ ] Sorties culturelles : 
   - [ ] Films en salle de cinéma. 
   - [ ] Films vus via des plateformes en ligne ? _Borner la question aux nouveaux films qui traduisent l'activité actuelle du cinéma et non l'activité passée. On aurait ainsi l'impact de la fabrication (avec des hypothèses d'allocations d'impact) + l'impact du média (en salle ou en ligne)_
   - [ ] Sortie au musée. _Note : suite à une échange avec le SNELAC - Syndicat National des Espaces de Loisirs, d'Attractions et Culturels, ce dernier fédère notamment des musées mais aucun de leur adhérant n'a réalisé de Bilan GES/Bilan Carbone_
   - [ ] Concert en salle
   - [ ] Concert(s) en festival
   - [ ] Théâtre / Ballet / Opéra
- [ ] Pratiques musicales
- [ ] Édition
- [ ] Télé / radio
   - [ ] Redevances
   - [ ] Abonnements
   - [ ] Écoutes

**Comment by JuliePouliquen** [comment]
Plongeons un peu dans la culture...

Une [étude de l'INSEE de 2022](https://www.insee.fr/fr/statistiques/6535285?sommaire=6535307#:~:text=En%202017%2C%20les%20m%C3%A9nages%20consacrent%20en%20moyenne%203%2C8%20%25,services%20culturels%20(figure%201)) nous donne ceci : 1041€ / an / ménage, dont 26% services audiovisuels, 22% livres et presse, 19% sorties culturelles et diverstissement.
![image](https://github.com/incubateur-ademe/nosgestesclimat/assets/4005340/8c07eae4-40ef-4af5-a624-0f450051bc6e)

**Comment by Clemog** [comment]
Je te rejoins sur la modulation ! (A voir si elle doit être fait sur tout indépendamment ou collectivement)
A mon avis, le plus pertinent serait de baser chaque proposition de modulation par l'approche "dépense des ménages", peut etre que ça permettrait d'orienter également la question

**Comment by JuliePouliquen** [comment]
> A mon avis, le plus pertinent serait de baser chaque proposition de modulation par l'approche "dépense des ménages", peut etre que ça permettrait d'orienter également la question

Oui typiquement pour les sorties type musées, monuments... on peut approximer qu'une sortie = 20€ par personne avec une marge d'erreur acceptable, du coup "une par mois" = budget de 20€ par mois soit 240€ / an, ce qui situe Mme X dans le haut du panier concernant les musées, donc empreinte correspondant au haut du panier. C'est pas si "facile" pour toutes les catégories...

**Comment by JuliePouliquen** [comment]
Mmmmm en parcourant l'étude INSEEE avec les dépenses des ménages, j'avoue que je suis un peu perdue sur le fait de l'utiliser pour moduler : 

- En premier lieu il n'y a que des gros sous-postes type "services culturels" dont il sera difficile de sortir des pratiques plus fines.
- En second l'approche par décile me paraît très complexe pour une précision qui n'est pas à la hauteur de la complexité.
- En troisième à un moment il faut réussir à approximer les dépenses de l'utilisateur, or de ce côté-là c'est toujours un casse-tête (beaucoup de dépenses sont omises, la mémoire ne fonctionne pas bien sur ce type de choses).

On pourrait tester une autre méthode qui s'en approche mais que je qualifierais de plus "marché" : comparaison avec la fréquentation moyenne par les français de ce type d'établissement.

Par exemple pour les monuments / musées... nous avons [ce document](https://www.culture.gouv.fr/Media/Thematiques/Etudes-et-statistiques/Files/Publications/Culture-etudes/20212/Note-de-synthese-CREDOC) qui nous dit pour le patrimoine (R91) : 

- 30% de la population est "amateur" : plus de 3 visites annuelles
- 37% sont visiteurs occasionnels : 1 à 2 par an
- Le reste non-visiteur

Donc on demande le nombre de visites de patrimoine par an (1 à 2, plus de 3), on attribue 100% de la moyenne française à ceux répondant "1 à 2", 200% à ceux répondant "plus de 3" et zéro aux autres.

**Comment by Clemog** [comment]
> Par exemple pour les monuments / musées... nous avons [ce document](https://www.culture.gouv.fr/Media/Thematiques/Etudes-et-statistiques/Files/Publications/Culture-etudes/20212/Note-de-synthese-CREDOC) (La visite des musées, expositions et monuments en 2019, étude pour le ministère de la culture) qui nous dit pour le patrimoine (R91) :
> 
> * 30% de la population est "amateur" : plus de 3 visites annuelles
> * 37% sont visiteurs occasionnels : 1 à 2 par an
> * Le reste non-visiteur
> 
> Donc on demande le nombre de visites de patrimoine par an (1 à 2, plus de 3), on attribue 100% de la moyenne française à ceux répondant "1 à 2", 200% à ceux répondant "plus de 3" et zéro aux autres.

Hyper intéressant ! 
Pour l'attribution à chaque possibilité, ici, tu attribues 100% et 200% arbitrairement ou car on a environ 1/3 partout ?

On pourrait aussi se dire qu'on ramène l'empreinte de R91 à la visite ?

**Comment by JuliePouliquen** [comment]
> Pour l'attribution à chaque possibilité, ici, tu attribues 100% et 200% arbitrairement ou car on a environ 1/3 partout ?

Non pas fatalement, mais vu que c'était le cas ici, et que ça correspond aussi plus ou moins à une pratique "nulle, simple ou double", je trouvais que ça le faisait. À voir pour les autres !

**Comment by JuliePouliquen** [comment]
Pour la modulation des postes, voici les choix actuels : 

- Sorties type concerts / spectacles / théâtres / cinéma / cirque : demande du nombre de sorties par an (moyenne estimée à 6 quand on somme les pratiques du cinéma, théâtre, concert)
- Musées, monuments, zoos et bibliothèques : demande du nombre de sorties par an (en France on a 3 tiers à peu près : 1/3 zéro, 1/3 une à deux fois, 1/3 plus que ça)
- Édition : approche budgétaire, sachant que le budget moyen par français est de un peu moins de 10€ / mois, correspondant donc à la moyenne d'empreinte.
- Télévision / radio : approche budgétaire également, la moyenne étant d'un peu plus de 10€ / mois / français.
- Pratique d'un instrument de musique : simple "oui / non" et on attribue le poids du secteur aux pratiquants de manière égale (24% de pratiquants en France)
- Jeux de hasard et d'argent : simple "oui / non" et on attribue le poids du secteur aux pratiquants de manière égale (47% de joueurs en France)
