### ISSUE TITLE
Création d’un dépôt pour chacun des modèles Livraison et Numérique

### ISSUE THREAD

**Issue by Clemog** [incubateur-ademe/nosgestesclimat#1985]
- Nouveaux dépôt dans [incubateur-ademe](https://github.com/incubateur-ademe)
- Ajout d’un README.
- Référencer les différents dépôts entre-eux pour établir un corpus d’exemple de réutilisation.

## Todo

- [x] [`@incubateur-ademe/publicodes-negaoctet`](https://github.com/incubateur-ademe/publicodes-negaoctet)
- [x] [`@incubateur-ademe/publicodes-commun`](https://github.com/incubateur-ademe/publicodes-commun)
- [x] [`@incubateur-ademe/publicodes-model-template`](https://github.com/incubateur-ademe/publicodes-model-template)
- [x] [`@incubateur-ademe/publicodes-livraison`](https://github.com/incubateur-ademe/publicodes-impact-livraison) -> In progress

**Comment by EmileRolley** [comment]
## Tasks

- [x] [`@incubateur-ademe/modele-numerique`](https://github.com/incubateur-ademe/modele-numerique)
- [ ] L'utiliser dans `nosgestesclimat`
  - [ ] -> Créer `@incubateur-ademe/modele-co2-commun`
  - [ ] -> Gérer les multiples dépendances de paquets dans `publicodes-tools`
- [ ] `@incubateur-ademe/publicodes-modele-package-template`
- [ ] `@incubateur-ademe/modele-livraison`

**Comment by jeannelf** [comment]
Ca correspond à quoi cette issue deja @Clemog ? je sais pas trop quoi tester ahah

**Comment by Clemog** [comment]
Hum rien a tester pour cette issue
C'est le fait de sortir de NGC ces modèles
